### ISSUE TITLE
Amperfied connect.home discovery broken.

### ISSUE THREAD

**Issue by SebastianRinger** [nymea/nymea-plugins-modbus#141]
I recently tested an Amperfied connect.home wallbox (software version 2.0.0), and found that the Nymea discovery is not working (anymore?). I looked at the log, the IP of the wallbox is not even showing up in the discovery log. This might be related to a particular feature of the wallbox: you can't ping it. I sent a support request to Amperfied about this, and they said it's not a bug but intended behavior related to security. I imagine the discovery was working when it was programmed, so this is probably something Amperfied introduced with a recent firmware update.

What is still working, however, is the NetworkDeviceMonitor. You can give that the MAC address of the wallbox, and it will return the correct IP. If you change the plugin to manual configuration with the MAC address, everything else is still working.

**Comment by mzanetti** [comment]
According to Amperfied this behavior did not change and was already in 1.0.0. Nevertheless, I've updated to v 2.0.0 and tested. Works fine for me. nymea uses ARP requests for the discovery. In fact, the Monitor is what won't work properly as that one uses Ping but this plugin ignores the monitors unreachable event for this reason.
