### ISSUE TITLE
SunSpec SolarEdge Battery is listed twice

### ISSUE THREAD

**Issue by ljonka** [nymea/nymea-plugins-modbus#61]
![image](https://user-images.githubusercontent.com/7216603/159580861-0e46dd98-1a31-420b-8b56-6e624909b4b5.png)
After Updating to latest experimental version of sunspec plugin the storage is listed a second time.

Using nymea-app from snap, edge

**Comment by t-mon** [comment]
Fixed with https://github.com/nymea/nymea-plugins-modbus/pull/60/commits/5b8e71422c2d4e46f3205b92236a0e22985dcb95
