### ISSUE TITLE
Kostal: Total energy counters are wrong

### ISSUE THREAD

**Issue by mzanetti** [nymea/nymea-plugins-modbus#79]
EnergyExperience: Thing meter for "KOSTAL Meter" seems to have been reset. Old value: 862.573 New value: 862.572.
Sep 04 21:15:36 nymea-energy nymead[317]:  I | EnergyExperience: Root meter seems to have been reset. Re-synching internal consumption counter.

This happens every once in a while, in average twice per hour. Perhaps a rounding error.

**Comment by mzanetti** [comment]
Also, there's more to it still: The totals counter values don't line up:
![image](https://user-images.githubusercontent.com/102573/189319985-5232fcc5-d405-4f48-b2ed-949c2d8fd1d6.png)

A car has been charged for 3 hours at 11kW, so the total for the day sould be somewhere around 33 - 40kWh, not 78kWh.

The totalEnergyReturned counter doesn't count up at all even though it does return quite a lot.

**Comment by mzanetti** [comment]
Looking at the screenshot, it seems the the "from grid" value would make sense for the "consumed" one, and the 23kW which are on top, could very well be the totalReturned instead.

**Comment by t-mon** [comment]
> EnergyExperience: Thing meter for "KOSTAL Meter" seems to have been reset. Old value: 862.573 New value: 862.572. Sep 04 21:15:36 nymea-energy nymead[317]: I | EnergyExperience: Root meter seems to have been reset. Re-synching internal consumption counter.
> 
> This happens every once in a while, in average twice per hour. Perhaps a rounding error.

Regarding this issue, the plugin does not round anywhere, the values comes as is from kostal as floating pointer. The only thing we could do here is to make sure the value is always bigger than the current one, otherwise I see no possibility how we can handle this.
